version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongocont
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend22:
    build: .
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://mongocont:27017"
    volumes:
      - ./:/app  # 🔹 Bind mount: Syncs local './app' directory with '/app' in the container
    working_dir: /app  # Set working directory to '/app'
  
volumes:
  mongodb_data:    


